[package]
name = "pueue"
description = "A shell commandline parallel processing management tool."
version = "0.1.0"
authors = ["Arne Beer <arne@twobeer.de>"]
repository = "https://github.com/nukesor/pueue-rs"
license = "MIT"
keywords = ["shell", "commandline", "parallel", "daemon"]

[badges]
travis-ci = { repository = "nukesor/pueue-rs", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
byteorder = "^1"
daemonize = "^0.2"
users = "^0.6"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
clap = "^2.31"
prettytable-rs = "^0.6"
config = "^0.8"
toml = "^0.4"
shellexpand = "^1.0"
futures = "^0.1"
tokio = "^0.1"
tokio-core = "^0.1"
tokio-io= "^0.1"
tokio-uds = "^0.1"
bytes = "^0.4"
