[package]
name = "pueue"
description = "A cli tool for managing long running shell commands."
version = "0.6.1"
authors = ["Arne Beer <contact@arne.beer>"]
homepage = "https://github.com/nukesor/pueue"
repository = "https://github.com/nukesor/pueue"
documentation = "https://docs.rs/pueue/"
license = "MIT"
keywords = ["shell", "command", "parallel", "task", "queue"]
readme = "README.md"
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[[bin]]
name = "pueue"
path = "client/main.rs"

[[bin]]
name = "pueued"
path = "daemon/main.rs"

[lib]
name = "pueue"
path = "shared/lib.rs"

[dependencies]
anyhow = "1"
async-std = { version = "1", features = ["attributes", "unstable"] }
dirs = "2"
chrono = { version = "^0.4", features = ["serde"] }
chrono-english = "^0.1.0"
rand = "^0.7"
strum = "^0.18"
strum_macros = "^0.18"
handlebars = "3"

bytes = "^0.5"
byteorder = "^1"
snap = "1"
serde = "^1.0"
bincode = "^1.2"
serde_json = "^1.0"
serde_yaml = "^0.8"
serde_derive = "^1.0"

log = "0.4"
config = "^0.10"
simplelog = { version = "0.8", default-features = false }
structopt = "0.3"
crossterm = "^0.17"
comfy-table= "0.1.0"
tempfile = "^3"

[target.'cfg(not(windows))'.dependencies]
users = "^0.10"
nix = "^0.17"

[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
procfs = "^0.7"

[target.'cfg(target_os = "macos")'.dependencies]
psutil = "^3"

[build-dependencies]
chrono = { version = "^0.4", features = ["serde"] }
chrono-english = "^0.1.0"
structopt = "0.3"
version_check = "^0.9"

[dev-dependencies]
proptest = "^0.9"
