[package]
name = "pueue"
description = "A shell commandline parallel processing management tool."
version = "0.1.0"
authors = ["Arne Beer <arne@twobeer.de>"]
repository = "https://github.com/nukesor/pueue-rs"
license = "MIT"
keywords = ["shell", "commandline", "parallel", "daemon"]

[badges]
travis-ci = { repository = "nukesor/pueue-rs", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
daemonize = "^0.3"
chrono = { version = "^0.4", features = ["serde"] }
users = "^0.7"
failure = "0.1.3"
failure_derive = "0.1.3"

byteorder = "^1"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"

clap = "^2.31"
prettytable-rs = "^0.7"
shellexpand = "^1.0"

config = "^0.9"
toml = "^0.4"

futures = "^0.1"
tokio = "^0.1"
tokio-core = "^0.1"
tokio-io= "^0.1"
tokio-uds = "^0.2"
bytes = "^0.4"
