[package]
name = "pueue"
description = "A cli tool for managing long running shell commands."
version = "0.1.0"
authors = ["Arne Beer <contact@arne.beer>"]
homepage = "https://github.com/nukesor/pueue"
repository = "https://github.com/nukesor/pueue"
documentation = "https://docs.rs/pueue/"
license = "MIT"
keywords = ["shell", "command", "parallel", "task", "queue"]
readme = "README.md"
edition = "2018"

[badges]
travis-ci = { repository = "nukesor/pueue", branch = "master" }
maintenance = { status = "actively-developed" }

[[bin]]
name = "completions_pueue"
path = "client/build_completion.rs"

[[bin]]
name = "pueue"
path = "client/main.rs"

[[bin]]
name = "pueued"
path = "daemon/main.rs"

[lib]
name = "pueue"
path = "shared/lib.rs"

[dependencies]
anyhow = "1"
async-std = { version = "1", features = ["attributes", "unstable"] }
dirs = "2"
users = "^0.9"
chrono = { version = "^0.4", features = ["serde"] }
rand = "^0.7"
nix = "0.16"
strum = "0.17"
strum_macros = "0.17"

bytes = "^0.5"
byteorder = "^1"
serde = "^1.0"
serde_json = "^1.0"
serde_yaml = "0.8"
serde_derive = "^1.0"

log = "0.4"
config = "^0.10"
simplelog = "0.7"
structopt = "0.3"
crossterm = "^0.14"
comfy-table= "0.0.4"
tempfile = "^3"
