[package]
name = "pueue"
description = "A shell commandline parallel processing management tool."
version = "0.1.0"
authors = ["Arne Beer <arne@twobeer.de>"]
repository = "https://github.com/nukesor/pueue-rs"
license = "MIT"
keywords = ["shell", "commandline", "parallel", "daemon", "queue", "scheduler"]
edition = "2018"

[badges]
travis-ci = { repository = "nukesor/pueue-rs", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
daemonize = "^0.4"
chrono = { version = "^0.4", features = ["serde"] }
users = "^0.9"
anyhow = "1"

byteorder = "^1"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"

clap = "^2.31"
prettytable-rs = "^0.8"
shellexpand = "^1.0"

config = "^0.9"
toml = "^0.5"

tokio = "0.2.0-alpha.6"
bytes = "^0.4"
uuid = { version = "^0.8", features = ["serde", "v4"] }

strum = "0.16"
strum_macros = "0.16"
