name: Test build

on:
  push:
    banches:
      -master
  pull_request:

jobs:
  publish:
    name: Test building for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # This should work with only the `include`s but it currently doesn't because of this bug:
        # https://github.community/t5/How-to-use-Git-and-GitHub/GitHub-Actions-Matrix-options-dont-work-as-documented/td-p/29558
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@v1

    - name: Run tests
      run: cargo test --verbose

    - name: Build the binary
      run: cargo build --all
